import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
const root=path.resolve('..');let fixtures;
test.beforeAll(()=>{fixtures=JSON.parse(execFileSync('php',['tests/browser-fixture.php','create'],{cwd:root,encoding:'utf8'}))});
test.afterAll(()=>{if(fixtures)execFileSync('php',['tests/browser-fixture.php','cleanup',String(fixtures.a.id),String(fixtures.b.id)],{cwd:root})});
async function login(page,person){await page.goto('./');await page.getByLabel('Email hoặc số điện thoại').fill(person.email);await page.getByLabel('Mật khẩu',{exact:true}).fill(fixtures.password);await page.getByRole('button',{name:'Vào BumpLocket'}).click();await expect(page.getByRole('heading',{name:'Những điều nhỏ, niềm vui to.'})).toBeVisible();}
test('Two friends: invitation, photo, consent, GPS, stop and mobile layout',async({page,browser})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const contextB=await browser.newContext({baseURL:process.env.BROWSER_TEST_URL||'https://chamcong.shop/thiepcuoisonline/',viewport:{width:390,height:844},permissions:['geolocation'],geolocation:{latitude:10.77,longitude:106.7}});
 const bob=await contextB.newPage();
 try {
 await login(page,fixtures.a);await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
 await page.locator('.sidebar').getByRole('button',{name:'Bạn bè',exact:true}).click();
 await page.getByPlaceholder('Email hoặc số điện thoại').fill(fixtures.b.email);await page.getByRole('button',{name:'Mời',exact:true}).click();
 await expect(page.locator('.main-column .friend')).toContainText('Đang chờ đồng ý');
 await login(bob,fixtures.b);await bob.locator('.mobile-nav').getByRole('button',{name:'Bạn bè',exact:true}).click();
 await bob.getByRole('button',{name:'Đồng ý',exact:true}).click();
 await expect(bob.locator('.main-column .friend')).toContainText('Đang online');
 await bob.locator('.mobile-nav').getByRole('button',{name:'Tin nhắn',exact:true}).click();
 await bob.locator('.conversation-list > button').first().click();
 await bob.getByPlaceholder('Nhập tin nhắn…').fill('Tin nhắn kiểm thử');await bob.locator('.chat-panel form').getByRole('button',{name:'Gửi'}).click();
 await expect(bob.locator('.message-stream')).toContainText('Tin nhắn kiểm thử');
 await page.reload();await page.locator('.sidebar').getByRole('button',{name:'Tin nhắn',exact:true}).click();await page.locator('.conversation-list > button').first().click();
 await expect(page.locator('.message-stream')).toContainText('Tin nhắn kiểm thử',{timeout:10000});
 await page.reload();await page.locator('.sidebar').getByRole('button',{name:'Bạn bè',exact:true}).click();
 await expect(page.locator('.main-column .bump-button')).toBeVisible();
 await page.locator('.main-column .bump-button').click();await page.getByRole('button',{name:'Đồng ý & gửi Bump'}).click();
 await expect(bob.getByRole('heading',{name:/muốn chia sẻ vị trí/})).toBeVisible({timeout:20000});
 await bob.getByRole('button',{name:'Đồng ý chia sẻ 15 phút'}).click();
 await expect(bob.getByRole('button',{name:'Bật GPS cho phiên này'})).toBeVisible({timeout:20000});
 await expect(bob.locator('.mapboxgl-canvas')).toBeVisible({timeout:10000});
 await bob.getByRole('button',{name:'Bật GPS cho phiên này'}).click();
 await expect(bob.locator('.coordinates')).toContainText('10.77000',{timeout:20000});
 await expect(page.locator('.coordinates')).toContainText('10.77000',{timeout:20000});
 await bob.getByRole('button',{name:'Dừng chia sẻ',exact:true}).click();
 await expect(bob.locator('.live-map')).toHaveCount(0);
 await expect(page.locator('.live-map')).toHaveCount(0,{timeout:20000});
 await page.locator('.sidebar').getByRole('button',{name:'Chụp ảnh',exact:true}).click();
 const image=await bob.screenshot();
 await page.locator('input[type=file]').setInputFiles({name:'moment.png',mimeType:'image/png',buffer:image});
 await page.getByPlaceholder('Hôm nay của bạn thế nào?').fill('Khoảnh khắc kiểm thử riêng tư');
 await page.getByRole('button',{name:'Chia sẻ với bạn bè',exact:true}).click();
 await expect(page.locator('.moment-card')).toHaveCount(1);
 await bob.locator('.mobile-nav').getByRole('button',{name:'Khoảnh khắc',exact:true}).click();
 await expect(bob.locator('.moment-card')).toHaveCount(1);
 await bob.locator('.moment-actions button').first().click();
 await expect(bob.locator('.moment-actions .liked')).toContainText('1');
 await bob.locator('.moment-actions button').nth(1).click();
 await bob.getByPlaceholder('Gửi một lời nhắn…').fill('Đã nhận ảnh!');
 await bob.locator('.comments').getByRole('button',{name:'Gửi',exact:true}).click();
 await expect(bob.locator('.comments')).toContainText('Đã nhận ảnh!');
 const downloaded=bob.waitForEvent('download');
 await bob.getByRole('link',{name:'Tải ảnh'}).click();
 expect((await downloaded).suggestedFilename()).toContain('bumplocket-');
 await bob.screenshot({path:'test-results/feed-mobile.png',fullPage:true});
 await page.locator('.sidebar').getByRole('button',{name:'Cá nhân',exact:true}).click();
 await page.locator('.profile-header input[type=file]').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:image});
 await page.getByRole('button',{name:'Cập nhật',exact:true}).click();await expect(page.locator('.profile-header .avatar img')).toBeVisible({timeout:10000});
 await page.getByPlaceholder('Bạn đang nghĩ gì?').fill('Bài viết chỉ có chữ');await page.getByRole('button',{name:'Đăng bài',exact:true}).click();
 await expect(page.locator('.profile-page .moment-card').filter({hasText:'Bài viết chỉ có chữ'})).toBeVisible();
 expect(await bob.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 expect(errors).toEqual([]);
 } finally {await contextB.close();}
});
